import type { ReactNode } from 'react';

import '@/styles/index.css';
import { Header, Footer, Theme } from '@/components';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Theme>
          <Header />
          <main className="flex-1 flex flex-col">{children}</main>
          <Footer />
        </Theme>
      </body>
    </html>
  );
}
