import type { ReactNode } from "react";

import "@/styles/globals.css";

import { Inter, PT_Serif } from "next/font/google";

import { Header, Footer, Theme } from "@/components";

import GlobalData from "../content/global/index.json";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const serif = PT_Serif({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--serif",
});

const sans = Inter({
  subsets: ["latin"],
  variable: "--sans",
});

export default function RootLayout({ children }: { children: ReactNode }) {
  const { footer, header } = GlobalData;
  const cnBody = `min-h-screen flex flex-col ${serif.variable} ${sans.variable}`;
  return (
    <html lang="en">
      <body className={cnBody}>
        <Theme>
          <Header {...header} />
          <main className="flex-1 flex flex-col">{children}</main>
          <Footer {...footer} />
        </Theme>
      </body>
    </html>
  );
}
